### ISSUE TITLE
"My Boards" section is not listed correctly

### ISSUE THREAD

**Issue by hokster7** [tungnguyenson/gmail-to-trello-extension#1]
Thanks for GMail-to-Trello. It's a life-saver when using Trello to keep track of some e-mail correspondences.

Sadly, its drop-down list has a section "My Boards", but shows a list of boards that I have already closed rather than the ones that are open. I'm confused as to why it should do this!

**Comment by tungnguyenson** [comment]
Are you a developer? If yes, you may use inspector tool have a look at what data was received. It can help you and me to investigate what was wrong

**Comment by hokster7** [comment]
Sorry for delayed reply. Yes I'm a developer (being on GitHub and everything!)... I'm not entirely sure how to do that though. Can you elaborate a little bit? There's a tonne of "Sources" that get loaded so how do I locate the listing of boards? Cheers.

**Comment by acoven** [comment]
@fatuhoku Are you still seeing this problem?

**Comment by acoven** [comment]
I see the code to make sure a "closed" board isn't added to the list, so I'm closing this until we can confirm.
