### ISSUE TITLE
New Trello windows closing instantly

### ISSUE THREAD

**Issue by l-i-n-k** [tungnguyenson/gmail-to-trello-extension#10]
When opening new trello windows/tabs (e.g. from e-mail) the windows close instantly after loading.
I did disable the extension an everything works again.

**Comment by asteino** [comment]
I am also having this issue.

**Comment by acoven** [comment]
@asteino @l-i-n-k Are you still seeing this issue? Can you take a screen video of it happening, if so?

**Comment by l-i-n-k** [comment]
Yes, here you are: https://vimeo.com/198697425

**Comment by acoven** [comment]
@l-i-n-k Great, thank you. Would you mind doing it again with the Chrome developer tools open on the side--make sure the console is showing, then copy-paste back what's in it with your response.

**Comment by l-i-n-k** [comment]
This is what you get:
`Navigated to https://trello.com/
trello.min.js:9 Scripts may close only the windows that were opened by it.
(anonymous) @ trello.min.js:9`

**Comment by l-i-n-k** [comment]
![trello min js 9](https://cloud.githubusercontent.com/assets/784287/21805972/589294f2-d737-11e6-8faa-8d03952756aa.png)
This can only be reproduced while opening Trello in an existing browser window.

**Comment by acoven** [comment]
@l-i-n-k That's fantastic, thanks. Would you mind giving me a screen shot of the "Sources" panel where it says "Call stack"?

**Comment by acoven** [comment]
@l-i-n-k @asteino Can you try with the latest 2.4.3 extension and see if it still happens? And if so, please screen record again but with the Developer Tools window open in Console so I can see what's causing the window to close. I'm very interested in trying to figure out what is causing this.

**Comment by acoven** [comment]
@l-i-n-k @asteino Ping.

**Comment by l-i-n-k** [comment]
Sorry for the delay. Changed to a new Mac. Still experiencing the Problem.

**Comment by l-i-n-k** [comment]
Just a note: I am switching to Google Inbox and Gmail2Trello doesn’t support (does any extension yet) an integration.

**Comment by acoven** [comment]
@l-i-n-k @asteino Thanks, no plans to support Google Inbox. I still can't recreate this, so if we can get me steps that'd help a ton but seems unnecessary for you now. Feel free to join us at https://trello.com/b/CGU9BYgd/gmail-to-trello-development to debug. Cheers.

**Comment by pleivac** [comment]
@l-i-n-k how do you solve the problem? I'm experiencing that issue too.

**Comment by erezerezg** [comment]
Hello, I'm also experiencing this issue, but I don't have any Trello-related chrome extensions installed. The behavior occurs when accessing Trello links and attempting to open them in new tabs/windows.

- When I open a new, blank tab - everything works as expected
- In Firefox - everything works as expected even in aforementioned scenarios
