### ISSUE TITLE
you don't need access to all urls for this extension

### ISSUE THREAD

**Issue by vijayp** [tungnguyenson/gmail-to-trello-extension#11]
You can specify only gmail and trello URLs.
https://developer.chrome.com/extensions/match_patterns

**Comment by vijayp** [comment]
I'm going to fix this in a pull request, along with some potential XSS attacks and incorrect url matching (for instance, your script will attempt to inject content into www.myserver.com/mail.google.com/foo)

**Comment by acoven** [comment]
Closing this as fixed by #12
