### ISSUE TITLE
Trello button randomly disappears

### ISSUE THREAD

**Issue by ul8** [tungnguyenson/gmail-to-trello-extension#118]
The trello button just randomly disappears in my Gmail. Reloading Gmail fixes it most of the time, sometimes multiple reloads are required. 

Sometimes the button is on the inbox page but once I click on an email, there's not button there.

Is this a known issue? Anything I can do to help troubleshoot? I'm a web developer but not familiar with development in Gmail.

I'm on latest Chrome 60.0.3112.90 and using a free gmail account in case that matters.

Thanks!

**Comment by acoven** [comment]
Thanks @ul8! We took this convo to [GtT Trello Board](https://trello.com/b/CGU9BYgd/gmail-to-trello-extension)
