### ISSUE TITLE
Breaks Google Drive

### ISSUE THREAD

**Issue by aengeln** [tungnguyenson/gmail-to-trello-extension#2]
It seems that the extension breaks Google Drive. No documents can be opened when Gmail to Trello is running.

"Sorry there's a problem with this file. Please reload."

**Comment by tungnguyenson** [comment]
Are you sure? I mean does Google Drive work well when you disable Gmail to Trello extension?

Not happen in mine

**Comment by aengeln** [comment]
Yea... :(

I disabled all extensions, and re-enabled them one by one. Gmail to Trello was the culprit. The same thing happens to a colleague of mine. 

Do you use Google Apps or regular Gmail? We use Apps. 

--A

**Comment by tungnguyenson** [comment]
![screen shot 2014-01-23 at 22 40 54](https://f.cloud.github.com/assets/6003129/1985875/fbeb9b42-8444-11e3-8632-7978a0601983.png)

I'm ok with Google Drive. Maybe it conflicts with some other extensions. Can you help me by giving a screenshot, or pasting content of Console region? (Ctrl+Shift+I)

**Comment by aengeln** [comment]
Might have been a conflict, and the problem seem to have gone away all of a sudden. Possibly a conflict with Plus for Trello, which was recently updated.

But alas, all is well, and I can keep enjoying Gmail to Trello. :)

**Comment by rmeekers** [comment]
No problem over here...

**Comment by acoven** [comment]
Closing this issue as cannot repro.
