### ISSUE TITLE
Doesn't play well with Rapportive GMail plugin

### ISSUE THREAD

**Issue by hokster7** [tungnguyenson/gmail-to-trello-extension#4]
Rapportive and Gmail-to-Trello integration plugin fight for the same screen space on GMail, resulting in a beautiful mess of words overlaid on top of each other, each obscuring the elements of the other.

**Reproduction**

Just install Rapportive and activate the Gmail-to-Trello integration plugin and you'll see what I mean.

**Comment by tungnguyenson** [comment]
@fatuhoku Strangely I added Rapportive but did not see the overlap. I've just increase z-index for safety. Can you check again?

**Comment by acoven** [comment]
@fatuhoku Could you confirm you're still seeing this? Otherwise we should close this.
