### ISSUE TITLE
Direct link to email

### ISSUE THREAD

**Issue by jonasob** [tungnguyenson/gmail-to-trello-extension#5]
It would be hugely useful if when selecting "Link back to Gmail", the links placed in the mail link _specifically_ to that exact email, rather than a search.

**Comment by tungnguyenson** [comment]
There are always two options: Search | Direct. Did you ignore the "Direct" link?

**Comment by jonasob** [comment]
Hmm. No, there's no Direct link on the cards it create here. Are there any
known situations where such a link would not appear?

**Comment by tungnguyenson** [comment]
Can you show up Console log output?

**Comment by jonasob** [comment]
Got it - I was just being stupid. It works perfectly fine :-)
(It wasn't immediately clear to me that the username part linked to the
exact email, while the hostname portion linked only to gmail).

Jonas

**Comment by acoven** [comment]
Closing this as Not A Bug.
