### ISSUE TITLE
CSS conflict

### ISSUE THREAD

**Issue by itsmartin** [tungnguyenson/gmail-to-trello-extension#6]
I had an issue with some content not showing up as it should on a site (unrelated to gmail or trello), and I've managed to track the source of the problem down to this extension. The content in question was in a div with CSS class "hidden". Searching through my extensions folder I found this extension's `style.css` includes on line 1:

```
.hidden {display: none}
```

Disabling gmail to trello resolved the issue for me, so I'm fairly sure this was the culprit.

I'm not familiar enough with how extensions work to know what the best fix/workaround for this would be, but thought it was worth reporting.

**Comment by tungnguyenson** [comment]
Thanks martin. Doesn't "hidden" suppose to be invisible?

I've removed the "hidden" CSS code anyway

**Comment by itsmartin** [comment]
Thanks. In the case of this specific site, it's a forum that uses the CSS class `hidden` in the forum moderator's view to apply a light grey style to a post that has been marked as hidden from the public.

So having the "display: none" in there was making such posts invisible to moderators too, which was confusing.

Thanks for the fix, anyway. I love this extension and wouldn't have liked to have to do without it :)

**Comment by kalupa** [comment]
Hey, I've added a quick fix to this as per https://github.com/tungbi/gmail-to-trello-extension/pull/7 ~ no need to remove the class, just makes sure that it's targeting the correct popup instead of anything with class 'hidden'
