### ISSUE TITLE
Plugin stops at Loading trello...

### ISSUE THREAD

**Issue by jesustorresdev** [tungnguyenson/gmail-to-trello-extension#9]
The first time I try to use the plugin it opens a dialog that shows "Loading trello..." but nothing happens and the inspector console shows an error:

GET https://api.trello.com/1/members/me?key=c50413b23ee49ca49a5c75ccf32d0459&token=f58266d94bfb85cbbeefd8bd3c42620b74d56900a65731c791c0ba0091441471 401 (Unauthorized) 

If I try again, the form in the dialog get showed but I don't see any board in the dropdown list.

**Comment by olafgeibig** [comment]
I have the same problem. How can I force Gmail to Trello to re-authorize at Trello? I reinstalled the extension an even deleted the extension folder, but still the same. If I execute the request against api.trello.com in the browser it says 'invalid token'

**Comment by olafgeibig** [comment]
Allright, found it: Ctrl-Shift-Del to enter 'delete browsing data' and select 'Hosted app data' only and then proceed.

**Comment by acoven** [comment]
@aplatanado @olafgeibig Safe to assume you aren't seeing these issues any more?

**Comment by jesustorresdev** [comment]
I'm not using GMail anymore so I removed the extension some month ago.

But I've reinstalled it to test and now the extension doesn't do anything. Neither It add the "add card" button to the GMail interface nor the button in the extension bar do anything when is clicked.

**Comment by acoven** [comment]
Do you have JavaScript turned off? Can you copy-paste a screenshot of your extensions page showing it loaded?

**Comment by jesustorresdev** [comment]
No. I don't. I have Javascript enabled. 

Here are the screenshots of my entire extensions page:

![image](https://cloud.githubusercontent.com/assets/266452/21804011/bcc3e984-d724-11e6-9a6c-0c647e136ce5.png)
![image](https://cloud.githubusercontent.com/assets/266452/21804019/c570fd88-d724-11e6-9d03-1d40a5abefbe.png)
![image](https://cloud.githubusercontent.com/assets/266452/21804022/cb9def40-d724-11e6-8765-69aca8ac1981.png)
![image](https://cloud.githubusercontent.com/assets/266452/21804028/d2fee0c8-d724-11e6-8862-4757447d629e.png)
![image](https://cloud.githubusercontent.com/assets/266452/21804036/d7e0455a-d724-11e6-9632-6c34013182d5.png)

**Comment by acoven** [comment]
@aplatanado Maybe the Trello credentials have grown stale. Please try this:
1. Ctrl-Shift-Del to enter 'delete browsing data' and select 'Hosted app data' only and then proceed.
2. Re-authenticate with your latest Trello credentials

**Comment by jesustorresdev** [comment]
@acoven I have deleted 'Hosted app data' but I don't see any change. How can I re-authenticate? The extension icon neither have any option for Trello authentication nor do anything when is clicked.

**Comment by acoven** [comment]
@aplatanado Thanks! When you first click the "Boards" pop-up, it will ask you to authenticate against Trello. Make sure you have any pop-up blockers turned off before you click on it.

**Comment by jesustorresdev** [comment]
Hi @acoven. I don't have any pop-up blockers. Only the one build-in Chrome. In any case, I have disabled it and all extension but happen the same.

Tomorrow a will try to test the extension in another version of Chrome.

**Comment by acoven** [comment]
@aplatanado Bizarre. Let me know what you find.

**Comment by jesustorresdev** [comment]
Hi @acoven.

It works fine. I tried other Chromes in other systems and with some accounts and it works. So, I removed this with all its configuration and reinstalled it again. Now, it works here too.

![image](https://cloud.githubusercontent.com/assets/266452/22085741/4f2ec3f8-ddcd-11e6-80b7-b06004caf339.png)

And I didn't see this issue.

Thank you.

**Comment by acoven** [comment]
Oh that's so great. If it has a problem again, post again at the dev Trello board here: https://trello.com/b/CGU9BYgd/gmail-to-trello-development
